theme: jekyll-theme-slate
title: COVID em Casa
url: https://covid-em-casa.info
slug: covid-em-casa
description: A collaborative guide to COVID-19 care
show_downloads: false
github:
  is_project_page: false
